---
title: "Responsiveness in immigration enforcement"
author: "Alexandria King "
description: "Do higher rates of youth voter tunrout leade to more liberal results  "
output:
  distill::distill_article:
    self_contained: false
---



Milestone 2 



Do higher rates of young voter turnout among the voting age population have an effect on the results of elections? In this study I hope to examine the effects that increases or decreases have on electoral results. I hypothesize that the as the share of young voters in the population turning out ot vote increases the more democratic or liberal electoral results will be. Conversely, I expect that as the rate of youth voter turnout decreases that the country will experience more conservative shifts in electoral results. In order to measure this I will take data form the census bureau measuring rates of voter turnout and registration from 1964-2020 and join it with data from the clerk at the US House of Representatives showing the proportion of democrats to Republicans that is inclusive of the same years as the data from the Census Bureau. I will need to create a csv file of this data-- however once that is completed it can be read into R and perhaps I can use a left join function to merge the data sets together. My explanatory variable of interest therefore will be rates of voter turnout among voters aged 18-29 in the US from 1964-2020 and perhaps even changes in rates of voter turnout among this group. The outcome variable of interest will be the number of Democrats in Congress in a given year. The data from the clerk's office at the House provides breakdowns of the specific number of Democrats and Republicans. Thus if we measure larger shares of Democrats in Congress during times of increasing rates of young voter turnout as modeled by a positive coefficient from running a regression, this observance would support my thesis. On the other hand if I run a regression and fidn that the oppositie is true, that larger shares of young voters mobilizing in an election was associated with higher shares of Republicans being elected this would quite cealry disprove my hypothesis. The more realistic scenario that would fail to prove my hypothesis is if when if I run a regression and there is no association, and,or weak association between youth voter turnout and shares of Democrats in Congress.  



https://www.census.gov/data/tables/time-series/demo/voting-and-registration/voting-historical-time-series.html

https://history.house.gov/Institution/Party-Divisions/Party-Divisions/